name: Generate Chisel Scala CLI Example

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  generate_scala_cli_example:
    name: Generate Scala CLI Example
    uses: ./.github/workflows/build-scala-cli-example.yml

  publish_example:
    name: Generate Chisel Scala CLI Example
    needs: [generate_scala_cli_example]
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Download Generated CLI Example
        uses: actions/download-artifact@v6
        with:
          name: chisel-example.scala
      - name: Display Example
        run: |
          echo '```scala' >> $GITHUB_STEP_SUMMARY
          cat chisel-example.scala >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Upload To Release Page
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # 2.4.1
        with:
          files: chisel-example.scala
